---
autodetect: false
strictness: veryhigh
doc-warnings: true
test-warnings: true

mccabe:
  options:
    max-complexity: 11

pep8:
  options:
    max-line-length: 99
  disable:
    - N815

pylint:
  options:
    max-args: 8
    max-attributes: 12
    max-line-length: 99
    max-module-lines: 1250
  disable:
    - C0111
    - C0103
    - C0209
    - F0401
    - R0903
    - R1705
    - W0703

pep257:
  disable:
    - D104
    - D203
    - D213
    - D406
    - D407
    - D413
