---
services:
  ejabberd:
    build:
      context: .
      dockerfile: Dockerfile.ejabberd
    environment:
      - CTL_ON_CREATE=register admin ejabberd admin ;
                      register echelon ejabberd echelon ;
                      register xpartamupp ejabberd xpartamupp ;
                      register player1 ejabberd player1 ;
                      register player2 ejabberd player2 ;
                      register player3 ejabberd player3
    extra_hosts:
      - "ejabberd:127.0.0.1"
    ports:
      - 3478:3478/udp
      - 5222:5222
      - 5280:5280
      - 5443:5443

  echelon:
    build:
      context: .
      dockerfile: Dockerfile.echelon
    extra_hosts:
      - "ejabberd:127.0.0.1"
    depends_on:
      - ejabberd

  xpartamupp:
    build:
      context: .
      dockerfile: Dockerfile.xpartamupp
    extra_hosts:
      - "ejabberd:127.0.0.1"
    depends_on:
      - ejabberd
