FROM ghcr.io/processone/ejabberd:22.05

COPY --chown=ejabberd:ejabberd ./docker/ejabberd.yml /opt/ejabberd/conf/ejabberd.yml
RUN mkdir -p /opt/ejabberd/.ejabberd-modules/sources
COPY --chown=ejabberd:ejabberd mod_ipstamp /opt/ejabberd/.ejabberd-modules/sources/mod_ipstamp
